name: Dependabot auto-merge
on: pull_request_target
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: 'Auto approve PR by Dependabot'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: '${{ secrets.ACTION_BOT_TOKEN }}'
      - name: 'Comment merge command'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.ACTION_BOT_TOKEN }}
          script: |
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@dependabot squash and merge'
            })